version: "3"
services:
  postgres:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: {}
